swagger: "2.0"
info:
  description: This is the swagger file that describes the sieve light api
  version: "1.0.0"
  title: Swagger REST for sieve light api
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api/alert"

# Paths supported by the server application
paths:
  /light/red:
    get:
      operationId: "light.red"
      tags:
        - "Alert.Light"
      summary: "The set red light"
      description: "Use light device to display a red light"
      responses:
        200:
          description: "Successful : A red light is displayed."
          schema:
            type: "boolean"