swagger: "2.0"
info:
  description: This is the swagger file that describes the sieve light api
  version: "1.0.0"
  title: Swagger REST for sieve light api
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api/alert"

# Paths supported by the server application
paths:
  /light/critical:
    get:
      operationId: "light.critical"
      parameters:
        - name: blink
          description: Duration in seconds when the alert is blinking.
          in: query
          type: integer
          default: 10
          required: false
        - name: bright
          description: Bright intensity of the lights.
          in: query
          type: number
          minimum: 0.0
          maximum: 1.0
          default: 0.5
          required: false
      tags:
        - "Alert.Light"
      summary: Sets red light."
      description: "Use light device to display a critical alert."
      responses:
        200:
          description: "Successful : A red light is displayed."
          schema:
            type: "boolean"
  /light/warning:
    get:
      operationId: "light.warning"
      parameters:
        - name: blink
          description: Duration in seconds when the alert is blinking.
          in: query
          type: integer
          default: 10
          required: false
        - name: bright
          description: Bright intensity of the lights.
          in: query
          type: number
          minimum: 0.0
          maximum: 1.0
          default: 0.5
          required: false
      tags:
        - "Alert.Light"
      summary: Sets orange light."
      description: "Use light device to display a medium alert."
      responses:
        200:
          description: "Successful : An orange light is displayed."
          schema:
            type: "boolean"
  /light/info:
    get:
      operationId: "light.info"
      parameters:
        - name: blink
          description: Duration in seconds when the alert is blinking.
          in: query
          type: integer
          default: 10
          required: false
        - name: bright
          description: Bright intensity of the lights.
          in: query
          type: number
          minimum: 0.0
          maximum: 1.0
          default: 0.5
          required: false
      tags:
        - "Alert.Light"
      summary: Sets green light."
      description: "Use light device to display a no alert"
      responses:
        200:
          description: "Successful : A green light is displayed."
          schema:
            type: "boolean"
  /light/clear:
    get:
      operationId: "light.clear"    
      tags:
        - "Alert.Light"
      summary: "Clears all the lights."
      description: "Swithes off all the light whatever their position."
      responses:
        200:
          description: "Successful : All the lights are switched off."
          schema:
            type: "boolean"